# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af31594e87a8ded0f0bfeaae2c4b00038e73bea45423c98d60f03f71375383080f35465713832c64b1ffb6286542a4da5be319b220bd4c92e18cd885206dcb71
  PUBLISHABLE_KEY: "pk_test_6pRNASCoBOKtIshFeQd4XMUh"
  SECRET_KEY: "sk_test_BQokikJOvBiI2HlWgH4olfQ2"
test:
  secret_key_base: d3eb6fc96296ea98fc10b807e28ff70c43527ead1008929670e305d1346189c655407fcb56792fdbe6857ab94fa0dc3bdb0ba9559474379168183d8de47500ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
